package/procps-ng: fix build with BR2_PACKAGE_SYSTEMD enable
After update to v4.0.4, props-ng build fails on linker error if If
BR2_PACKAGE_SYSTEMD is enabled:

/build/output/host/lib/gcc/x86_64-buildroot-linux-gnu/12.4.0/../../../../x86_64-buildroot-linux-gnu/bin/ld: src/w.o: undefined reference to symbol 'sd_session_get_uid@@LIBSYSTEMD_209'
/build/output/host/lib/gcc/x86_64-buildroot-linux-gnu/12.4.0/../../../../x86_64-buildroot-linux-gnu/bin/ld: /build/output/host/x86_64-buildroot-linux-gnu/sysroot/lib64/libsystemd.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Add lsystemd to configure arguments if systemd is enabled to fix this.

Signed-off-by: Jan Čermák <sairon@sairon.cz>